
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sheik
 */
public class dashboard extends javax.swing.JFrame {

   private static final String username= "root";
    private static final String password= "";
    private static final String dataConn= "jdbc:mysql://localhost/project";
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }

    String s,nn;
    public void userdata(String st,String n){
        s=st;
        nn=n;
         }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        elephantvote = new javax.swing.JButton();
        lionvote = new javax.swing.JButton();
        eaglevote = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Online Voting System");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Elephant Team");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 190, -1));

        jLabel2.setBackground(new java.awt.Color(102, 0, 102));
        jLabel2.setForeground(new java.awt.Color(153, 255, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Groups Icon/elephant.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 150, 140));

        jLabel7.setBackground(new java.awt.Color(102, 0, 102));
        jLabel7.setForeground(new java.awt.Color(153, 255, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Groups Icon/lion.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 150, 140));

        jLabel8.setBackground(new java.awt.Color(102, 0, 102));
        jLabel8.setForeground(new java.awt.Color(153, 255, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Groups Icon/eagle.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 150, 140));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Groups");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 260, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Lion Team");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 160, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Eagle Team");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 160, -1));

        elephantvote.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        elephantvote.setText("Vote");
        elephantvote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elephantvoteActionPerformed(evt);
            }
        });
        jPanel2.add(elephantvote, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 140, 50));

        lionvote.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lionvote.setText("Vote");
        lionvote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lionvoteActionPerformed(evt);
            }
        });
        jPanel2.add(lionvote, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 140, 50));

        eaglevote.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        eaglevote.setText("Vote");
        eaglevote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eaglevoteActionPerformed(evt);
            }
        });
        jPanel2.add(eaglevote, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 140, 50));

        logout.setBackground(new java.awt.Color(255, 102, 102));
        logout.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, 120, 50));

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elephantvoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elephantvoteActionPerformed
               
        String a = "1";
        String b = "0";
        
        
        if(nn.equals(b)){
            
        
        try{
            
            //========================Vote Count============================================
            
            Class.forName("com.mysql.jdbc.Driver");
           
            con = DriverManager.getConnection(dataConn,username,password);
            
            String sql1 = "select tvotes from groups where id=3";
            pst = con.prepareStatement(sql1);
            
            rs = pst.executeQuery();
            String news=null;
            
            if(rs.next()){
                  news = rs.getString(1);
                   
            }
            
            int abc= Integer.valueOf (news);
           abc=abc+1;
           
           String sql2 = "UPDATE groups SET id='3',gname='Elephant Team',tvotes=? WHERE id=3 ";
           con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root","");
           pst =con.prepareStatement(sql2);
           pst.setInt(1,abc);
           pst.executeUpdate();
            
            
            
            
            //========================================================================
           
           //=======================User vote count==================================
            
           String sql3 = "UPDATE user SET status=?,vote=? WHERE stud_id=? ";
           
           con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root","");
           pst =con.prepareStatement(sql3);
           pst.setString(1,a);
           pst.setString(2,"3");
           pst.setString(3,s);
           
           
           
          pst.executeUpdate();
          after_vote av = new after_vote();
          av.setVisible(true);
          this.setVisible(false);
          
          
           
              
            //========================================================================
           
       }catch(Exception ex){
           JOptionPane.showMessageDialog(null,ex);   
       }  
        
        }
        
        else {
            JOptionPane.showMessageDialog(null,"Already voted!!");
        }
        
        
        
        
        
    }//GEN-LAST:event_elephantvoteActionPerformed

    private void lionvoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lionvoteActionPerformed
       
        String a = "1";
        String b = "0";
        
        if(nn.equals(b)){
            
        
        try{
            
            //========================Vote Count============================================
            
            Class.forName("com.mysql.jdbc.Driver");
           
            con = DriverManager.getConnection(dataConn,username,password);
            
            String sql4 = "select tvotes from groups where id=1";
            pst = con.prepareStatement(sql4);
            
            rs = pst.executeQuery();
            String news=null;
            
            if(rs.next()){
                  news = rs.getString(1);
                   
            }
            
            int abc= Integer.valueOf (news);
           abc=abc+1;
           
           String sql5 = "UPDATE groups SET id='1',gname='Lion Team',tvotes=? WHERE id=1 ";
           con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root","");
           pst =con.prepareStatement(sql5);
           pst.setInt(1,abc);
           pst.executeUpdate();
            
            
            
            
            //========================================================================
           
           //=======================User vote count==================================
            
           String sql6 = "UPDATE user SET status=?,vote=? WHERE stud_id=? ";
           
           con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root","");
           pst =con.prepareStatement(sql6);
           pst.setString(1,a);
           pst.setString(2,"1");
           pst.setString(3,s);
           
           
           
          pst.executeUpdate();
          after_vote av = new after_vote();
          av.setVisible(true);
          this.setVisible(false);
          
           
             
            //========================================================================
           
       }catch(Exception ex){
           JOptionPane.showMessageDialog(null,ex);   
       }  
        
        }
        
        else {
            JOptionPane.showMessageDialog(null,"Already voted!!");
        }
        
    }//GEN-LAST:event_lionvoteActionPerformed

    private void eaglevoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eaglevoteActionPerformed
             
        String a = "1";
        String b = "0";
        
        if(nn.equals(b)){
            
        
        try{
            
            //========================Vote Count============================================
            
            Class.forName("com.mysql.jdbc.Driver");
           
            con = DriverManager.getConnection(dataConn,username,password);
            
            String sql7 = "select tvotes from groups where id=2";
            pst = con.prepareStatement(sql7);
            
            rs = pst.executeQuery();
            String news=null;
            
            if(rs.next()){
                  news = rs.getString(1);
                   
            }
            
            int abc= Integer.valueOf (news);
           abc=abc+1;
           
           String sql8 = "UPDATE groups SET id='2',gname='Eagle Team',tvotes=? WHERE id=2 ";
           con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root","");
           pst =con.prepareStatement(sql8);
           pst.setInt(1,abc);
           pst.executeUpdate();
            
            
            
            
            //========================================================================
           
           //=======================User vote count==================================
            
           String sql9 = "UPDATE user SET status=?,vote=? WHERE stud_id=? ";
           
           con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root","");
           pst =con.prepareStatement(sql9);
           pst.setString(1,a);
           pst.setString(2,"2");
           pst.setString(3,s);
           
           
           
          pst.executeUpdate();
          after_vote av = new after_vote();
          av.setVisible(true);
          this.setVisible(false);
          
           
               
            //========================================================================
           
       }catch(Exception ex){
           JOptionPane.showMessageDialog(null,ex);   
       }  
        
        }
        
        else {
            JOptionPane.showMessageDialog(null,"Already voted!!");
        }

    }//GEN-LAST:event_eaglevoteActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eaglevote;
    private javax.swing.JButton elephantvote;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lionvote;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
