
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asif
 */
public class project_admin extends javax.swing.JFrame {

    private static final String username= "root";
    private static final String password= "";
    private static final String dataConn= "jdbc:mysql://localhost/project";
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form project_admin
     */
    public project_admin() {
        initComponents();
    }
    
   public String winner(int a, int b, int c){
       String winner;
       if(a>b && a>c){
               
               winner="Lion Team";
           
       }
       else if(b>a && b>c){
           winner="Eagle Team";
           
       }
       else if(c>a && c>b){
           winner="Elephant Team";
           
       }
       else if(a==b & a==c){
           winner = "Tie!! No one wins";
           
       }
       else if(a>c && b>c && a==b)
       {
           winner = "Tie!! No one wins";
       }
       else if(a>b && c>b && a==c)
       {
           winner = "Tie!! No one wins";
       }
       else if(c>a && b>a && c==b)
       {
           winner = "Tie!! No one wins";
       }
       else{
           winner = "Error";
       }
       
       
       
       return winner;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        alluser = new javax.swing.JButton();
        votes = new javax.swing.JButton();
        result = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Admin");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 260, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Online Voting System");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        alluser.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        alluser.setText("All User");
        alluser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alluserActionPerformed(evt);
            }
        });
        jPanel4.add(alluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 340, 60));

        votes.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        votes.setText("Votes");
        votes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votesActionPerformed(evt);
            }
        });
        jPanel4.add(votes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 340, 60));

        result.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        result.setText("Result");
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });
        jPanel4.add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 340, 60));

        logout.setBackground(new java.awt.Color(255, 102, 102));
        logout.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel4.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 120, 50));

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alluserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alluserActionPerformed
       all_user a = new all_user();
       a.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_alluserActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutActionPerformed

    private void votesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votesActionPerformed
       votes v = new votes();
       v.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_votesActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        
        result r = new result();
        try{
            
            
            //-------------------------------------------------------------------------------------------------------------
             Class.forName("com.mysql.jdbc.Driver");
           
            con = DriverManager.getConnection(dataConn,username,password);
            
            String sql1 = "select tvotes from groups where id=1";
            pst = con.prepareStatement(sql1);
            
            rs = pst.executeQuery();
            String ta=null;
            
            if(rs.next()){
                  ta = rs.getString(1);
                   
                 }
            int tta= Integer.valueOf (ta);
            
            
            
            //-------------------------------------------------------------------------------------------------------------
            
            
            //-------------------------------------------------------------------------------------------------------------
            
            Class.forName("com.mysql.jdbc.Driver");
           
            con = DriverManager.getConnection(dataConn,username,password);
            
            String sql2 = "select tvotes from groups where id=2";
            pst = con.prepareStatement(sql2);
            
            rs = pst.executeQuery();
            String tb=null;
            
            if(rs.next()){
                  tb = rs.getString(1);
                   
                 }
            int ttb= Integer.valueOf (tb);
            
            
            
            //-------------------------------------------------------------------------------------------------------------
            
            Class.forName("com.mysql.jdbc.Driver");
           
            con = DriverManager.getConnection(dataConn,username,password);
            
            String sql3 = "select tvotes from groups where id=3";
            pst = con.prepareStatement(sql3);
            
            rs = pst.executeQuery();
            String tc=null;
            
            if(rs.next()){
                  tc = rs.getString(1);
                   
                 }
            int ttc= Integer.valueOf (tc);
            
            
            
            //-------------------------------------------------------------------------------------------------------------
            
            //-------------------------------------------------------------------------------------------------------------
         
        r.getwinner(ta, tb, tc);
        String ww = winner(tta,ttb,ttc);
        r.winner(ww);
        
        }catch(Exception ex){
            
        }
 
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_resultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alluser;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logout;
    private javax.swing.JButton result;
    private javax.swing.JButton votes;
    // End of variables declaration//GEN-END:variables
}
